name = "Default Configuration"

#All units are in radians and microns
[geometry] 
hole_diameter   = 9e-3
beam_x = [-0.00792,-0.0085,  0.0 ,  0.02130] #was 953
beam_y = [0.019,  -0.01484,  0.0 , -0.00015]
pix = 24.0

[servo]
#Phasor offsets in microns. Need to convert...
gd_phasor_offset = [5.073, -2.203, 0.088, 3.855, -5.234, 2.61]
dl_type = "rmn"

[wave]
K1  = 2.1 
K2  = 2.3 
